name: mineru-local
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - "--extra-index-url https://download.pytorch.org/whl/cu128"
      - uv
      - "mineru[all]==3.4.4"
      - "torch==2.8.0+cu128"
      - "torchvision==0.23.0+cu128"
